// Code generated by eventsource-protobuf. DO NOT EDIT.
// source: commands.proto

package clients

// AggregateID implements the eventsource.Command interface for Create
func (c *Create) AggregateID() string {
	return c.Id
}

// AggregateID implements the eventsource.Command interface for Activate
func (c *Activate) AggregateID() string {
	return c.Id
}

// AggregateID implements the eventsource.Command interface for DeActivate
func (c *DeActivate) AggregateID() string {
	return c.Id
}

// AggregateID implements the eventsource.Command interface for ChangeName
func (c *ChangeName) AggregateID() string {
	return c.Id
}
