// Code generated by eventsource-protobuf. DO NOT EDIT.
// source: events.proto

package orders

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
	"time"

	"github.com/vancelongwill/eventsource"
	"google.golang.org/protobuf/proto"
)

type serializer struct {
}

func (s *serializer) MarshalEvent(event eventsource.Event) (eventsource.Record, error) {
	data, err := MarshalEvent(event)
	if err != nil {
		return eventsource.Record{}, err
	}

	return eventsource.Record{
		Version: event.EventVersion(),
		Data:    data,
	}, nil
}

func (s *serializer) UnmarshalEvent(record eventsource.Record) (eventsource.Event, error) {
	return UnmarshalEvent(record.Data)
}

func NewSerializer() eventsource.Serializer {
	return &serializer{}
}

func (m *OrderCreated) AggregateID() string { return m.Id }
func (m *OrderCreated) EventVersion() int   { return int(m.Version) }
func (m *OrderCreated) EventAt() time.Time  { return time.Unix(m.At, 0) }

func (m *OrderCancelled) AggregateID() string { return m.Id }
func (m *OrderCancelled) EventVersion() int   { return int(m.Version) }
func (m *OrderCancelled) EventAt() time.Time  { return time.Unix(m.At, 0) }

func (m *OrderAudited) AggregateID() string { return m.Id }
func (m *OrderAudited) EventVersion() int   { return int(m.Version) }
func (m *OrderAudited) EventAt() time.Time  { return time.Unix(m.At, 0) }

func (m *OrderNameChanged) AggregateID() string { return m.Id }
func (m *OrderNameChanged) EventVersion() int   { return int(m.Version) }
func (m *OrderNameChanged) EventAt() time.Time  { return time.Unix(m.At, 0) }

func (m *OrderShipped) AggregateID() string { return m.Id }
func (m *OrderShipped) EventVersion() int   { return int(m.Version) }
func (m *OrderShipped) EventAt() time.Time  { return time.Unix(m.At, 0) }


func MarshalEvent(event eventsource.Event) ([]byte, error) {
	container := &EventContainer{}

	switch v := event.(type) {

	case *OrderCreated:
		container.Type = 2
		container.OrderCreated = v

	case *OrderCancelled:
		container.Type = 3
		container.OrderCancelled = v

	case *OrderAudited:
		container.Type = 4
		container.OrderAudited = v

	case *OrderNameChanged:
		container.Type = 5
		container.OrderNameChanged = v

	case *OrderShipped:
		container.Type = 6
		container.OrderShipped = v

	default:
		return nil, fmt.Errorf("Unhandled type, %v", event)
	}

	data, err := proto.Marshal(container)
	if err != nil {
		return nil, err
	}

	return data, nil
}

func UnmarshalEvent(data []byte) (eventsource.Event, error) {
	container := &EventContainer{}
	err := proto.Unmarshal(data, container)
	if err != nil {
		return nil, err
	}

	var event interface{}
	switch container.Type {

	case 2:
		event = container.OrderCreated

	case 3:
		event = container.OrderCancelled

	case 4:
		event = container.OrderAudited

	case 5:
		event = container.OrderNameChanged

	case 6:
		event = container.OrderShipped

	default:
		return nil, fmt.Errorf("Unhandled type, %v", container.Type)
	}

	return event.(eventsource.Event), nil
}

type Encoder struct {
	w io.Writer
}

func (e *Encoder) WriteEvent(event eventsource.Event) (int, error) {
	data, err := MarshalEvent(event)
	if err != nil {
		return 0, err
	}

	// Write the length of the marshaled event as uint64
	//
	buffer := make([]byte, 8)
	binary.LittleEndian.PutUint64(buffer, uint64(len(data)))
	if _, err := e.w.Write(buffer); err != nil {
		return 0, err
	}

	n, err := e.w.Write(data)
	if err != nil {
		return 0, err
	}

	return n + 8, nil
}

func NewEncoder(w io.Writer) *Encoder {
	return &Encoder{
		w: w,
	}
}

type Decoder struct {
	r       *bufio.Reader
	scratch *bytes.Buffer
}

func (d *Decoder) readN(n uint64) ([]byte, error) {
	d.scratch.Reset()
	for i := uint64(0); i < n; i++ {
		b, err := d.r.ReadByte()
		if err != nil {
			return nil, err
		}
		if err := d.scratch.WriteByte(b); err != nil {
			return nil, err
		}
	}
	return d.scratch.Bytes(), nil
}

func (d *Decoder) ReadEvent() (eventsource.Event, error) {
	data, err := d.readN(8)
	if err != nil {
		return nil, err
	}
	length := binary.LittleEndian.Uint64(data)

	data, err = d.readN(length)
	if err != nil {
		return nil, err
	}

	event, err := UnmarshalEvent(data)
	if err != nil {
		return nil, err
	}

	return event, nil
}

func NewDecoder(r io.Reader) *Decoder {
	return &Decoder{
		r:       bufio.NewReader(r),
		scratch: bytes.NewBuffer(nil),
	}
}

type Builder struct {
	id      string
	version int
	Events  []eventsource.Event
}

func NewBuilder(id string, version int) *Builder {
	return &Builder {
		id:      id,
		version: version,
	}
}

func (b *Builder) nextVersion() int32 {
	b.version++
	return int32(b.version)
}


func (b *Builder) OrderCreated(by string, ) {
	event := &OrderCreated{
		Id:      b.id,
		Version: b.nextVersion(),
		At:      time.Now().Unix(),
		By: by,
	}
	b.Events = append(b.Events, event)
}

func (b *Builder) OrderShipped(destination string, ) {
	event := &OrderShipped{
		Id:      b.id,
		Version: b.nextVersion(),
		At:      time.Now().Unix(),
		Destination: destination,
	}
	b.Events = append(b.Events, event)
}

func (b *Builder) OrderCancelled(cancelreason string, ) {
	event := &OrderCancelled{
		Id:      b.id,
		Version: b.nextVersion(),
		At:      time.Now().Unix(),
		CancelReason: cancelreason,
	}
	b.Events = append(b.Events, event)
}

func (b *Builder) OrderAudited() {
	event := &OrderAudited{
		Id:      b.id,
		Version: b.nextVersion(),
		At:      time.Now().Unix(),
	}
	b.Events = append(b.Events, event)
}

func (b *Builder) OrderNameChanged(firstname string, lastname string, ) {
	event := &OrderNameChanged{
		Id:      b.id,
		Version: b.nextVersion(),
		At:      time.Now().Unix(),
		FirstName: firstname,
		LastName: lastname,
	}
	b.Events = append(b.Events, event)
}

